version: '3'
services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "8000:5000"
    volumes:
      - ./server:/app
    environment:
      - FLASK_ENV=development

  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    ports:
      - "4173:80"
    volumes:
      - ./web:/app
