services:
  api:
    build:
      context: .
      dockerfile: ./server/Dockerfile.production
    container_name: react-ui
    env_file: .env.production
    image: api-production:latest  # Use Heroku registry format
    restart: unless-stopped
    depends_on:
      - mongo
    networks:
      - peak-performance

  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile.production
    container_name: node-api
    env_file: .env.production
    image: client-production:latest  # Use Heroku registry format
    restart: unless-stopped
    networks:
      - peak-performance
    depends_on:
      - api

networks:
  peak-performance:
    driver: bridge
