version: '3'
services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "8000:5000"
    volumes:
      - ./server:/app
    environment:
      - FLASK_ENV=development

  frontend:
    build:
      context: ./menumatch
      dockerfile: Dockerfile.dev
    ports:
      - "8080:3000"
    volumes:
      - ./menumatch:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
