services:
  app:
    container_name: my_django_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./requirements.txt:/app/requirements.txt
      - ./my_project:/app/my_project
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_NAME=movie_data
      - DB_USER=selina
      - DB_PASSWORD=snowBall
      - DB_HOST=db
      - DB_PORT=3306
    command: ["sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]

  db:
    container_name: my_sql_db
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=movie_data
      - MYSQL_USER=selina
      - MYSQL_PASSWORD=snowBall
      - MYSQL_ROOT_PASSWORD=snowBall2024
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
