version: '3'
services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    environment:
      - FLASK_ENV=development

  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    ports:
      - "3000:5173"
    volumes:
      - ./web:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
