services:
  api:
    build:
      context: .
      dockerfile: ./client/Dockerfile.production
    env_file: ./.env.production
    image: registry.heroku.com/peak-performace/api-production:latest  # Use Heroku registry format
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - peak-performance

  client:
    build:
      context: .
      dockerfile: ./server/Dockerfile.production
    env_file: ./.env.production
    image: registry.heroku.com/peak-performace/client-production:latest  # Use Heroku registry format
    restart: unless-stopped
    networks:
      - peak-performance
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api

  # Add mongo service if needed, otherwise remove it.
  mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    networks:
      - peak-performance

volumes:
  mongo_data:
    driver: local

networks:
  peak-performance:
    driver: bridge
