version: '3'
services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    ports:
      - "8000:5000"
    environment:
      - FLASK_ENV=production

  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    ports:
      - "80:4173"
networks:
  t1:
    driver: bridge