version: '3'
services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production

  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
