# Your workflow name.
name: Deploy to heroku.

# Run workflow on every push to dev branch
on:
  push:
    branches: HW-166-add-tests-to-docker-container
# Your workflows jobs.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check-out your repository.
      - name: Checkout
        uses: actions/checkout@v2

      # Copy heroku.yml to the root directory
      #Trying to get this file to change so I can make a commit
      #- name: Copy heroku.yml to root
      #  run: cp ./code/heroku.yml ./

      # Set up Docker Buildx (optional, but recommended for multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1  

      # Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      # Log in to Docker Hub (if needed, otherwise skip this step)
      - name: Log in to Heroku Container Registry
        run: echo "${{ secrets.HEROKU_API_KEY }}" | docker login --username=__token__ --password-stdin registry.heroku.com

      # Build and tag Docker images using docker-compose.
      - name: Build and Tag Docker Images with Docker Compose
        run: |
          docker-compose -f ./code/docker-compose-production.yml build
      #docker tag code_server registry.heroku.com/{{ secrets.HEROKU_APP_NAME }}/api-production:latest
      #docker tag code_client registry.heroku.com/{{ secrets.HEROKU_APP_NAME }}/client-production:latest

      # Push Docker images to Heroku Container Registry.
      - name: Push Docker Images to Heroku
        run: |
          docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/api-production:latest
          docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/client-production:latest

      # Release the Docker images on Heroku.
      - name: Release Docker Images on Heroku
        run: |
          heroku container:release api client --app ${{ secrets.HEROKU_APP_NAME }}