name: CI Pipeline

on:
  push:
    branches:
      - '**'
    paths:
      - "code/frontend/**"
      - "code/backend/**"
      - "code/ai-service/fast-api/**"
      - "tests/**"

jobs:
  # Job 1: Lint and Test React Frontend
  frontend:
    name: React Frontend Linting and Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: cd code/frontend && npm install

      - name: Lint React code
        run: |
          cd code/frontend
          npx eslint . --rule 'max-len: off' --rule 'no-warning-comments: off'

      - name: Run React Unit Tests
        run: cd code/frontend && npm test

  # Job 2: Build and Test Spring Boot Backend
  backend:
    name: Spring Boot Backend Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Build and Test Spring Boot
        run: |
          cd code/backend/course-builder-chatbot-ms
          ./mvnw clean install
          ./mvnw test


  # Job 3: Lint, Test, and Deploy Python AI Service (FastAPI)
  python-ai-service-fastapi:
    name: Python AI Service (FastAPI) Linting and Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          cd code/ai-service/fast-api
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Lint Python code
        run: |
          cd code/ai-service/fast-api
          source venv/bin/activate
          flake8 --ignore=E501,E265 .

      - name: Run Python Unit Tests
        run: |
          cd code/ai-service/fast-api
          source venv/bin/activate
          pytest

  # Job 5: Cucumber BDD Tests (UI + API)
  bdd-tests:
    name: Cucumber BDD Testing (UI and API)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Install Chrome for Headless Mode
        run: sudo apt-get install -y google-chrome-stable

      - name: Install Maven and Run Cucumber Tests
        run: |
          cd tests
          mvn clean install
          mvn test

      - name: Archive Cucumber Reports
        uses: actions/upload-artifact@v2
        with:
          name: cucumber-reports
          path: tests/target/cucumber-reports/

  # Shared Job: Super-Linter
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
          IGNORE_ERRORS: "E501,E265"
