name: Node.js CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci
      working-directory: code/frontend

    - name: Build the project
      run: npm run build
      working-directory: code/frontend

    # Uncomment if you add tests in the future
    # - name: Run tests
    #   run: npm test
    #   working-directory: code/frontend

    - name: Deploy with gh-pages
      run: |
        npm install gh-pages --save-dev
        git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
      working-directory: code/frontend
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
