name: Django Test

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: docker-compose -f docker-compose.yml up -d

      - name: Wait for MySQL to be healthy
        run: |
          until [ "$(docker inspect -f '{{.State.Health.Status}}' my_sql_db)" == "healthy" ]; do
            echo "Waiting for MySQL to be healthy..."
            sleep 5
          done
          echo "MySQL is healthy."

      - name: Run migrations
        run: docker-compose exec app python manage.py migrate

      - name: Run tests
        run: docker-compose exec app python manage.py test

      - name: Shut down Docker Compose
        run: docker-compose -f docker-compose.yml down
