name: Django Test

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Install Docker Compose
        run: sudo apt-get install docker-compose -y

      - name: Set up Docker Compose and Build
        run: docker-compose -f code/docker-compose.yml up --build -d

      - name: Wait for Services to Start
        run: |
          echo "Waiting for services to start..."
          sleep 20

      - name: Wait for MySQL to be healthy
        run: |
          until [ "$(docker inspect -f '{{.State.Health.Status}}' my_sql_db)" == "healthy" ]; do
            echo "Waiting for MySQL to be healthy..."
            sleep 5
          done
          echo "MySQL is healthy."

      - name: Run Django Tests
        run: docker-compose -f code/docker-compose.yml exec app python manage.py test

      - name: Shut down Docker Compose
        run: docker-compose -f code/docker-compose.yml down
